name: Go
permissions:
  contents: read
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:

  build:
    strategy:
      matrix:
        go-version: ['stable', 'oldstable']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v5
    - name: Install Go
      if: success()
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Run tests
      run: make test
